// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.1
// source: logsproxy/v1/logs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_LEGACY      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_WHITELISTED AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_VAC_BANNED  AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_LEGACY",
		2: "ACCOUNT_STATUS_WHITELISTED",
		3: "ACCOUNT_STATUS_VAC_BANNED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_LEGACY":      1,
		"ACCOUNT_STATUS_WHITELISTED": 2,
		"ACCOUNT_STATUS_VAC_BANNED":  3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_logsproxy_v1_logs_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_logsproxy_v1_logs_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{0}
}

type AdminLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action    string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Issuer    string `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Target    string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Details   string `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *AdminLogEntry) Reset() {
	*x = AdminLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogEntry) ProtoMessage() {}

func (x *AdminLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogEntry.ProtoReflect.Descriptor instead.
func (*AdminLogEntry) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AdminLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AdminLogEntry) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AdminLogEntry) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AdminLogEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type AdminLogUpdatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminLogUpdatesRequest) Reset() {
	*x = AdminLogUpdatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLogUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogUpdatesRequest) ProtoMessage() {}

func (x *AdminLogUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogUpdatesRequest.ProtoReflect.Descriptor instead.
func (*AdminLogUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{1}
}

type AdminLogUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *AdminLogEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *AdminLogUpdatesResponse) Reset() {
	*x = AdminLogUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLogUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogUpdatesResponse) ProtoMessage() {}

func (x *AdminLogUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogUpdatesResponse.ProtoReflect.Descriptor instead.
func (*AdminLogUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *AdminLogUpdatesResponse) GetEntry() *AdminLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AdminsLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminsLogsRequest) Reset() {
	*x = AdminsLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminsLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminsLogsRequest) ProtoMessage() {}

func (x *AdminsLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminsLogsRequest.ProtoReflect.Descriptor instead.
func (*AdminsLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{3}
}

type AdminsLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*AdminLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *AdminsLogsResponse) Reset() {
	*x = AdminsLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminsLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminsLogsResponse) ProtoMessage() {}

func (x *AdminsLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminsLogsResponse.ProtoReflect.Descriptor instead.
func (*AdminsLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{4}
}

func (x *AdminsLogsResponse) GetEntries() []*AdminLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type JoinLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	KeyHash    string        `protobuf:"bytes,2,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	TrustLevel uint32        `protobuf:"varint,3,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	Name       string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt  int64         `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ipv4       uint32        `protobuf:"fixed32,6,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Status     AccountStatus `protobuf:"varint,7,opt,name=status,proto3,enum=logsproxy.v1.AccountStatus" json:"status,omitempty"`
}

func (x *JoinLogEntry) Reset() {
	*x = JoinLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogEntry) ProtoMessage() {}

func (x *JoinLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogEntry.ProtoReflect.Descriptor instead.
func (*JoinLogEntry) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{5}
}

func (x *JoinLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *JoinLogEntry) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *JoinLogEntry) GetTrustLevel() uint32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *JoinLogEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinLogEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JoinLogEntry) GetIpv4() uint32 {
	if x != nil {
		return x.Ipv4
	}
	return 0
}

func (x *JoinLogEntry) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

type JoinLogUpdatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinLogUpdatesRequest) Reset() {
	*x = JoinLogUpdatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLogUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogUpdatesRequest) ProtoMessage() {}

func (x *JoinLogUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogUpdatesRequest.ProtoReflect.Descriptor instead.
func (*JoinLogUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{6}
}

type JoinLogUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *JoinLogEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *JoinLogUpdatesResponse) Reset() {
	*x = JoinLogUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLogUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogUpdatesResponse) ProtoMessage() {}

func (x *JoinLogUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogUpdatesResponse.ProtoReflect.Descriptor instead.
func (*JoinLogUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{7}
}

func (x *JoinLogUpdatesResponse) GetEntry() *JoinLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type JoinLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinLogsRequest) Reset() {
	*x = JoinLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogsRequest) ProtoMessage() {}

func (x *JoinLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogsRequest.ProtoReflect.Descriptor instead.
func (*JoinLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{8}
}

type JoinLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*JoinLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *JoinLogsResponse) Reset() {
	*x = JoinLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogsResponse) ProtoMessage() {}

func (x *JoinLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogsResponse.ProtoReflect.Descriptor instead.
func (*JoinLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{9}
}

func (x *JoinLogsResponse) GetEntries() []*JoinLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PlayerProfileEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  int64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	KeyHash    string `protobuf:"bytes,2,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	TrustLevel uint32 `protobuf:"varint,3,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	Username   string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *PlayerProfileEntry) Reset() {
	*x = PlayerProfileEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfileEntry) ProtoMessage() {}

func (x *PlayerProfileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfileEntry.ProtoReflect.Descriptor instead.
func (*PlayerProfileEntry) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerProfileEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerProfileEntry) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *PlayerProfileEntry) GetTrustLevel() uint32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *PlayerProfileEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PlayerProfilesUpdatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerProfilesUpdatesRequest) Reset() {
	*x = PlayerProfilesUpdatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfilesUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesUpdatesRequest) ProtoMessage() {}

func (x *PlayerProfilesUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesUpdatesRequest.ProtoReflect.Descriptor instead.
func (*PlayerProfilesUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{11}
}

type PlayerProfilesUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *PlayerProfileEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *PlayerProfilesUpdatesResponse) Reset() {
	*x = PlayerProfilesUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfilesUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesUpdatesResponse) ProtoMessage() {}

func (x *PlayerProfilesUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesUpdatesResponse.ProtoReflect.Descriptor instead.
func (*PlayerProfilesUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerProfilesUpdatesResponse) GetEntry() *PlayerProfileEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PlayerProfilesLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerProfilesLogsRequest) Reset() {
	*x = PlayerProfilesLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfilesLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesLogsRequest) ProtoMessage() {}

func (x *PlayerProfilesLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesLogsRequest.ProtoReflect.Descriptor instead.
func (*PlayerProfilesLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{13}
}

type PlayerProfilesLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PlayerProfileEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PlayerProfilesLogsResponse) Reset() {
	*x = PlayerProfilesLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logsproxy_v1_logs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfilesLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesLogsResponse) ProtoMessage() {}

func (x *PlayerProfilesLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesLogsResponse.ProtoReflect.Descriptor instead.
func (*PlayerProfilesLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerProfilesLogsResponse) GetEntries() []*PlayerProfileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_logsproxy_v1_logs_proto protoreflect.FileDescriptor

var file_logsproxy_v1_logs_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x6c,
	0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c, 0x6f, 0x67, 0x73, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x8f, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x17, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x12, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73,
	0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x22, 0xe4, 0x01, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x74, 0x72, 0x75, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x04, 0x69, 0x70, 0x76, 0x34, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x4a, 0x6f,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x16, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c,
	0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22,
	0x11, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x48, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x8a, 0x01, 0x0a,
	0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x74, 0x72, 0x75, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x57, 0x0a, 0x1d, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x6f, 0x67, 0x73,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x58, 0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2a, 0x89, 0x01, 0x0a, 0x0d, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x41,
	0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x41,
	0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x45,
	0x47, 0x41, 0x43, 0x59, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x57, 0x48, 0x49, 0x54, 0x45, 0x4c, 0x49,
	0x53, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x56, 0x41, 0x43, 0x5f, 0x42, 0x41, 0x4e,
	0x4e, 0x45, 0x44, 0x10, 0x03, 0x32, 0xc4, 0x01, 0x0a, 0x0f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c,
	0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x6c,
	0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4f, 0x0a, 0x0a, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1f, 0x2e, 0x6c, 0x6f, 0x67, 0x73,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x4c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x6f, 0x67,
	0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73,
	0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xba, 0x01, 0x0a,
	0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5d, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x23, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x49,
	0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1d, 0x2e, 0x6c, 0x6f, 0x67,
	0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c, 0x6f, 0x67, 0x73,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf4, 0x01, 0x0a, 0x15, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x2e, 0x6c,
	0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x67, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x27, 0x2e,
	0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x2f, 0x70, 0x72, 0x2d, 0x6c, 0x6f, 0x67, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f,
	0x6c, 0x6f, 0x67, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logsproxy_v1_logs_proto_rawDescOnce sync.Once
	file_logsproxy_v1_logs_proto_rawDescData = file_logsproxy_v1_logs_proto_rawDesc
)

func file_logsproxy_v1_logs_proto_rawDescGZIP() []byte {
	file_logsproxy_v1_logs_proto_rawDescOnce.Do(func() {
		file_logsproxy_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_logsproxy_v1_logs_proto_rawDescData)
	})
	return file_logsproxy_v1_logs_proto_rawDescData
}

var file_logsproxy_v1_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logsproxy_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_logsproxy_v1_logs_proto_goTypes = []interface{}{
	(AccountStatus)(0),                    // 0: logsproxy.v1.AccountStatus
	(*AdminLogEntry)(nil),                 // 1: logsproxy.v1.AdminLogEntry
	(*AdminLogUpdatesRequest)(nil),        // 2: logsproxy.v1.AdminLogUpdatesRequest
	(*AdminLogUpdatesResponse)(nil),       // 3: logsproxy.v1.AdminLogUpdatesResponse
	(*AdminsLogsRequest)(nil),             // 4: logsproxy.v1.AdminsLogsRequest
	(*AdminsLogsResponse)(nil),            // 5: logsproxy.v1.AdminsLogsResponse
	(*JoinLogEntry)(nil),                  // 6: logsproxy.v1.JoinLogEntry
	(*JoinLogUpdatesRequest)(nil),         // 7: logsproxy.v1.JoinLogUpdatesRequest
	(*JoinLogUpdatesResponse)(nil),        // 8: logsproxy.v1.JoinLogUpdatesResponse
	(*JoinLogsRequest)(nil),               // 9: logsproxy.v1.JoinLogsRequest
	(*JoinLogsResponse)(nil),              // 10: logsproxy.v1.JoinLogsResponse
	(*PlayerProfileEntry)(nil),            // 11: logsproxy.v1.PlayerProfileEntry
	(*PlayerProfilesUpdatesRequest)(nil),  // 12: logsproxy.v1.PlayerProfilesUpdatesRequest
	(*PlayerProfilesUpdatesResponse)(nil), // 13: logsproxy.v1.PlayerProfilesUpdatesResponse
	(*PlayerProfilesLogsRequest)(nil),     // 14: logsproxy.v1.PlayerProfilesLogsRequest
	(*PlayerProfilesLogsResponse)(nil),    // 15: logsproxy.v1.PlayerProfilesLogsResponse
}
var file_logsproxy_v1_logs_proto_depIdxs = []int32{
	1,  // 0: logsproxy.v1.AdminLogUpdatesResponse.entry:type_name -> logsproxy.v1.AdminLogEntry
	1,  // 1: logsproxy.v1.AdminsLogsResponse.entries:type_name -> logsproxy.v1.AdminLogEntry
	0,  // 2: logsproxy.v1.JoinLogEntry.status:type_name -> logsproxy.v1.AccountStatus
	6,  // 3: logsproxy.v1.JoinLogUpdatesResponse.entry:type_name -> logsproxy.v1.JoinLogEntry
	6,  // 4: logsproxy.v1.JoinLogsResponse.entries:type_name -> logsproxy.v1.JoinLogEntry
	11, // 5: logsproxy.v1.PlayerProfilesUpdatesResponse.entry:type_name -> logsproxy.v1.PlayerProfileEntry
	11, // 6: logsproxy.v1.PlayerProfilesLogsResponse.entries:type_name -> logsproxy.v1.PlayerProfileEntry
	2,  // 7: logsproxy.v1.AdminLogService.AdminLogUpdates:input_type -> logsproxy.v1.AdminLogUpdatesRequest
	4,  // 8: logsproxy.v1.AdminLogService.AdminsLogs:input_type -> logsproxy.v1.AdminsLogsRequest
	7,  // 9: logsproxy.v1.JoinLogService.JoinLogUpdates:input_type -> logsproxy.v1.JoinLogUpdatesRequest
	9,  // 10: logsproxy.v1.JoinLogService.JoinLogs:input_type -> logsproxy.v1.JoinLogsRequest
	12, // 11: logsproxy.v1.PlayerProfilesService.PlayerProfilesUpdates:input_type -> logsproxy.v1.PlayerProfilesUpdatesRequest
	14, // 12: logsproxy.v1.PlayerProfilesService.PlayerProfilesLogs:input_type -> logsproxy.v1.PlayerProfilesLogsRequest
	3,  // 13: logsproxy.v1.AdminLogService.AdminLogUpdates:output_type -> logsproxy.v1.AdminLogUpdatesResponse
	5,  // 14: logsproxy.v1.AdminLogService.AdminsLogs:output_type -> logsproxy.v1.AdminsLogsResponse
	8,  // 15: logsproxy.v1.JoinLogService.JoinLogUpdates:output_type -> logsproxy.v1.JoinLogUpdatesResponse
	10, // 16: logsproxy.v1.JoinLogService.JoinLogs:output_type -> logsproxy.v1.JoinLogsResponse
	13, // 17: logsproxy.v1.PlayerProfilesService.PlayerProfilesUpdates:output_type -> logsproxy.v1.PlayerProfilesUpdatesResponse
	15, // 18: logsproxy.v1.PlayerProfilesService.PlayerProfilesLogs:output_type -> logsproxy.v1.PlayerProfilesLogsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_logsproxy_v1_logs_proto_init() }
func file_logsproxy_v1_logs_proto_init() {
	if File_logsproxy_v1_logs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logsproxy_v1_logs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLogUpdatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLogUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminsLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminsLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLogUpdatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLogUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerProfileEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerProfilesUpdatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerProfilesUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerProfilesLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logsproxy_v1_logs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerProfilesLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logsproxy_v1_logs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_logsproxy_v1_logs_proto_goTypes,
		DependencyIndexes: file_logsproxy_v1_logs_proto_depIdxs,
		EnumInfos:         file_logsproxy_v1_logs_proto_enumTypes,
		MessageInfos:      file_logsproxy_v1_logs_proto_msgTypes,
	}.Build()
	File_logsproxy_v1_logs_proto = out.File
	file_logsproxy_v1_logs_proto_rawDesc = nil
	file_logsproxy_v1_logs_proto_goTypes = nil
	file_logsproxy_v1_logs_proto_depIdxs = nil
}
