// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: logsproxy/v1/logs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminAction int32

const (
	AdminAction_ADMIN_ACTION_UNSPECIFIED   AdminAction = 0
	AdminAction_ADMIN_ACTION_AA            AdminAction = 1
	AdminAction_ADMIN_ACTION_ALLOWEDID     AdminAction = 2
	AdminAction_ADMIN_ACTION_BAN           AdminAction = 3
	AdminAction_ADMIN_ACTION_BANID         AdminAction = 4
	AdminAction_ADMIN_ACTION_FLY           AdminAction = 5
	AdminAction_ADMIN_ACTION_HASH          AdminAction = 6
	AdminAction_ADMIN_ACTION_INIT          AdminAction = 7
	AdminAction_ADMIN_ACTION_KICK          AdminAction = 8
	AdminAction_ADMIN_ACTION_KILL          AdminAction = 9
	AdminAction_ADMIN_ACTION_MAPVOTE       AdminAction = 10
	AdminAction_ADMIN_ACTION_MAPVOTERESULT AdminAction = 11
	AdminAction_ADMIN_ACTION_MESSAGE       AdminAction = 12
	AdminAction_ADMIN_ACTION_RELOAD        AdminAction = 13
	AdminAction_ADMIN_ACTION_REPORT        AdminAction = 14
	AdminAction_ADMIN_ACTION_REPORTP       AdminAction = 15
	AdminAction_ADMIN_ACTION_RESIGN        AdminAction = 16
	AdminAction_ADMIN_ACTION_RESIGNALL     AdminAction = 17
	AdminAction_ADMIN_ACTION_RUNNEXT       AdminAction = 18
	AdminAction_ADMIN_ACTION_SAY           AdminAction = 19
	AdminAction_ADMIN_ACTION_SAYTEAM       AdminAction = 20
	AdminAction_ADMIN_ACTION_SCRAMBLE      AdminAction = 21
	AdminAction_ADMIN_ACTION_SETNEXT       AdminAction = 22
	AdminAction_ADMIN_ACTION_STOPSERVER    AdminAction = 23
	AdminAction_ADMIN_ACTION_SWAPTEAMS     AdminAction = 24
	AdminAction_ADMIN_ACTION_SWITCH        AdminAction = 25
	AdminAction_ADMIN_ACTION_TEMPBAN       AdminAction = 26
	AdminAction_ADMIN_ACTION_TICKETS       AdminAction = 27
	AdminAction_ADMIN_ACTION_TIMEBAN       AdminAction = 28
	AdminAction_ADMIN_ACTION_TIMEBANID     AdminAction = 29
	AdminAction_ADMIN_ACTION_UNBAN         AdminAction = 30
	AdminAction_ADMIN_ACTION_UNBANID       AdminAction = 31
	AdminAction_ADMIN_ACTION_UNBANNAME     AdminAction = 32
	AdminAction_ADMIN_ACTION_UNGRIEF       AdminAction = 33
	AdminAction_ADMIN_ACTION_WARN          AdminAction = 34
)

// Enum value maps for AdminAction.
var (
	AdminAction_name = map[int32]string{
		0:  "ADMIN_ACTION_UNSPECIFIED",
		1:  "ADMIN_ACTION_AA",
		2:  "ADMIN_ACTION_ALLOWEDID",
		3:  "ADMIN_ACTION_BAN",
		4:  "ADMIN_ACTION_BANID",
		5:  "ADMIN_ACTION_FLY",
		6:  "ADMIN_ACTION_HASH",
		7:  "ADMIN_ACTION_INIT",
		8:  "ADMIN_ACTION_KICK",
		9:  "ADMIN_ACTION_KILL",
		10: "ADMIN_ACTION_MAPVOTE",
		11: "ADMIN_ACTION_MAPVOTERESULT",
		12: "ADMIN_ACTION_MESSAGE",
		13: "ADMIN_ACTION_RELOAD",
		14: "ADMIN_ACTION_REPORT",
		15: "ADMIN_ACTION_REPORTP",
		16: "ADMIN_ACTION_RESIGN",
		17: "ADMIN_ACTION_RESIGNALL",
		18: "ADMIN_ACTION_RUNNEXT",
		19: "ADMIN_ACTION_SAY",
		20: "ADMIN_ACTION_SAYTEAM",
		21: "ADMIN_ACTION_SCRAMBLE",
		22: "ADMIN_ACTION_SETNEXT",
		23: "ADMIN_ACTION_STOPSERVER",
		24: "ADMIN_ACTION_SWAPTEAMS",
		25: "ADMIN_ACTION_SWITCH",
		26: "ADMIN_ACTION_TEMPBAN",
		27: "ADMIN_ACTION_TICKETS",
		28: "ADMIN_ACTION_TIMEBAN",
		29: "ADMIN_ACTION_TIMEBANID",
		30: "ADMIN_ACTION_UNBAN",
		31: "ADMIN_ACTION_UNBANID",
		32: "ADMIN_ACTION_UNBANNAME",
		33: "ADMIN_ACTION_UNGRIEF",
		34: "ADMIN_ACTION_WARN",
	}
	AdminAction_value = map[string]int32{
		"ADMIN_ACTION_UNSPECIFIED":   0,
		"ADMIN_ACTION_AA":            1,
		"ADMIN_ACTION_ALLOWEDID":     2,
		"ADMIN_ACTION_BAN":           3,
		"ADMIN_ACTION_BANID":         4,
		"ADMIN_ACTION_FLY":           5,
		"ADMIN_ACTION_HASH":          6,
		"ADMIN_ACTION_INIT":          7,
		"ADMIN_ACTION_KICK":          8,
		"ADMIN_ACTION_KILL":          9,
		"ADMIN_ACTION_MAPVOTE":       10,
		"ADMIN_ACTION_MAPVOTERESULT": 11,
		"ADMIN_ACTION_MESSAGE":       12,
		"ADMIN_ACTION_RELOAD":        13,
		"ADMIN_ACTION_REPORT":        14,
		"ADMIN_ACTION_REPORTP":       15,
		"ADMIN_ACTION_RESIGN":        16,
		"ADMIN_ACTION_RESIGNALL":     17,
		"ADMIN_ACTION_RUNNEXT":       18,
		"ADMIN_ACTION_SAY":           19,
		"ADMIN_ACTION_SAYTEAM":       20,
		"ADMIN_ACTION_SCRAMBLE":      21,
		"ADMIN_ACTION_SETNEXT":       22,
		"ADMIN_ACTION_STOPSERVER":    23,
		"ADMIN_ACTION_SWAPTEAMS":     24,
		"ADMIN_ACTION_SWITCH":        25,
		"ADMIN_ACTION_TEMPBAN":       26,
		"ADMIN_ACTION_TICKETS":       27,
		"ADMIN_ACTION_TIMEBAN":       28,
		"ADMIN_ACTION_TIMEBANID":     29,
		"ADMIN_ACTION_UNBAN":         30,
		"ADMIN_ACTION_UNBANID":       31,
		"ADMIN_ACTION_UNBANNAME":     32,
		"ADMIN_ACTION_UNGRIEF":       33,
		"ADMIN_ACTION_WARN":          34,
	}
)

func (x AdminAction) Enum() *AdminAction {
	p := new(AdminAction)
	*p = x
	return p
}

func (x AdminAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminAction) Descriptor() protoreflect.EnumDescriptor {
	return file_logsproxy_v1_logs_proto_enumTypes[0].Descriptor()
}

func (AdminAction) Type() protoreflect.EnumType {
	return &file_logsproxy_v1_logs_proto_enumTypes[0]
}

func (x AdminAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminAction.Descriptor instead.
func (AdminAction) EnumDescriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{0}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_LEGACY      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_WHITELISTED AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_VAC_BANNED  AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_LEGACY",
		2: "ACCOUNT_STATUS_WHITELISTED",
		3: "ACCOUNT_STATUS_VAC_BANNED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_LEGACY":      1,
		"ACCOUNT_STATUS_WHITELISTED": 2,
		"ACCOUNT_STATUS_VAC_BANNED":  3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_logsproxy_v1_logs_proto_enumTypes[1].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_logsproxy_v1_logs_proto_enumTypes[1]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{1}
}

type AdminLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action        AdminAction            `protobuf:"varint,2,opt,name=action,proto3,enum=logsproxy.v1.AdminAction" json:"action,omitempty"`
	ActionStr     string                 `protobuf:"bytes,3,opt,name=action_str,json=actionStr,proto3" json:"action_str,omitempty"`
	Issuer        string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Details       string                 `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLogEntry) Reset() {
	*x = AdminLogEntry{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogEntry) ProtoMessage() {}

func (x *AdminLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogEntry.ProtoReflect.Descriptor instead.
func (*AdminLogEntry) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AdminLogEntry) GetAction() AdminAction {
	if x != nil {
		return x.Action
	}
	return AdminAction_ADMIN_ACTION_UNSPECIFIED
}

func (x *AdminLogEntry) GetActionStr() string {
	if x != nil {
		return x.ActionStr
	}
	return ""
}

func (x *AdminLogEntry) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AdminLogEntry) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AdminLogEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type AdminLogUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    *uint64                `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3,oneof" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLogUpdatesRequest) Reset() {
	*x = AdminLogUpdatesRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLogUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogUpdatesRequest) ProtoMessage() {}

func (x *AdminLogUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogUpdatesRequest.ProtoReflect.Descriptor instead.
func (*AdminLogUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLogUpdatesRequest) GetLineNumber() uint64 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

type AdminLogUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AdminLogEntry         `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	LineNumber    uint64                 `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLogUpdatesResponse) Reset() {
	*x = AdminLogUpdatesResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLogUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLogUpdatesResponse) ProtoMessage() {}

func (x *AdminLogUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLogUpdatesResponse.ProtoReflect.Descriptor instead.
func (*AdminLogUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *AdminLogUpdatesResponse) GetEntry() *AdminLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *AdminLogUpdatesResponse) GetLineNumber() uint64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type AdminsLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminsLogsRequest) Reset() {
	*x = AdminsLogsRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminsLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminsLogsRequest) ProtoMessage() {}

func (x *AdminsLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminsLogsRequest.ProtoReflect.Descriptor instead.
func (*AdminsLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{3}
}

type AdminsLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AdminLogEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminsLogsResponse) Reset() {
	*x = AdminsLogsResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminsLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminsLogsResponse) ProtoMessage() {}

func (x *AdminsLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminsLogsResponse.ProtoReflect.Descriptor instead.
func (*AdminsLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{4}
}

func (x *AdminsLogsResponse) GetEntries() []*AdminLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type JoinLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	KeyHash       string                 `protobuf:"bytes,2,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	TrustLevel    uint32                 `protobuf:"varint,3,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ipv4          uint32                 `protobuf:"fixed32,6,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Status        AccountStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=logsproxy.v1.AccountStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLogEntry) Reset() {
	*x = JoinLogEntry{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogEntry) ProtoMessage() {}

func (x *JoinLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogEntry.ProtoReflect.Descriptor instead.
func (*JoinLogEntry) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{5}
}

func (x *JoinLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *JoinLogEntry) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *JoinLogEntry) GetTrustLevel() uint32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *JoinLogEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinLogEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JoinLogEntry) GetIpv4() uint32 {
	if x != nil {
		return x.Ipv4
	}
	return 0
}

func (x *JoinLogEntry) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

type JoinLogUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    *uint64                `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3,oneof" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLogUpdatesRequest) Reset() {
	*x = JoinLogUpdatesRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLogUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogUpdatesRequest) ProtoMessage() {}

func (x *JoinLogUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogUpdatesRequest.ProtoReflect.Descriptor instead.
func (*JoinLogUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{6}
}

func (x *JoinLogUpdatesRequest) GetLineNumber() uint64 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

type JoinLogUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *JoinLogEntry          `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	LineNumber    uint64                 `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLogUpdatesResponse) Reset() {
	*x = JoinLogUpdatesResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLogUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogUpdatesResponse) ProtoMessage() {}

func (x *JoinLogUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogUpdatesResponse.ProtoReflect.Descriptor instead.
func (*JoinLogUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{7}
}

func (x *JoinLogUpdatesResponse) GetEntry() *JoinLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *JoinLogUpdatesResponse) GetLineNumber() uint64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type JoinLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLogsRequest) Reset() {
	*x = JoinLogsRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogsRequest) ProtoMessage() {}

func (x *JoinLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogsRequest.ProtoReflect.Descriptor instead.
func (*JoinLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{8}
}

type JoinLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*JoinLogEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLogsResponse) Reset() {
	*x = JoinLogsResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLogsResponse) ProtoMessage() {}

func (x *JoinLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLogsResponse.ProtoReflect.Descriptor instead.
func (*JoinLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{9}
}

func (x *JoinLogsResponse) GetEntries() []*JoinLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PlayerProfileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	KeyHash       string                 `protobuf:"bytes,2,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	TrustLevel    uint32                 `protobuf:"varint,3,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfileEntry) Reset() {
	*x = PlayerProfileEntry{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfileEntry) ProtoMessage() {}

func (x *PlayerProfileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfileEntry.ProtoReflect.Descriptor instead.
func (*PlayerProfileEntry) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerProfileEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerProfileEntry) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *PlayerProfileEntry) GetTrustLevel() uint32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *PlayerProfileEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PlayerProfilesUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    *uint64                `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3,oneof" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfilesUpdatesRequest) Reset() {
	*x = PlayerProfilesUpdatesRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfilesUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesUpdatesRequest) ProtoMessage() {}

func (x *PlayerProfilesUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesUpdatesRequest.ProtoReflect.Descriptor instead.
func (*PlayerProfilesUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerProfilesUpdatesRequest) GetLineNumber() uint64 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

type PlayerProfilesUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *PlayerProfileEntry    `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	LineNumber    uint64                 `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfilesUpdatesResponse) Reset() {
	*x = PlayerProfilesUpdatesResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfilesUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesUpdatesResponse) ProtoMessage() {}

func (x *PlayerProfilesUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesUpdatesResponse.ProtoReflect.Descriptor instead.
func (*PlayerProfilesUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerProfilesUpdatesResponse) GetEntry() *PlayerProfileEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *PlayerProfilesUpdatesResponse) GetLineNumber() uint64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type PlayerProfilesLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfilesLogsRequest) Reset() {
	*x = PlayerProfilesLogsRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfilesLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesLogsRequest) ProtoMessage() {}

func (x *PlayerProfilesLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesLogsRequest.ProtoReflect.Descriptor instead.
func (*PlayerProfilesLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{13}
}

type PlayerProfilesLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PlayerProfileEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfilesLogsResponse) Reset() {
	*x = PlayerProfilesLogsResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfilesLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfilesLogsResponse) ProtoMessage() {}

func (x *PlayerProfilesLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfilesLogsResponse.ProtoReflect.Descriptor instead.
func (*PlayerProfilesLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerProfilesLogsResponse) GetEntries() []*PlayerProfileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Player query messages
type SearchPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"` // Search by name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlayersRequest) Reset() {
	*x = SearchPlayersRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlayersRequest) ProtoMessage() {}

func (x *SearchPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlayersRequest.ProtoReflect.Descriptor instead.
func (*SearchPlayersRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{15}
}

func (x *SearchPlayersRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type PlayerSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHash       string                 `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OtherNames    []string               `protobuf:"bytes,3,rep,name=other_names,json=otherNames,proto3" json:"other_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSearchResult) Reset() {
	*x = PlayerSearchResult{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSearchResult) ProtoMessage() {}

func (x *PlayerSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSearchResult.ProtoReflect.Descriptor instead.
func (*PlayerSearchResult) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerSearchResult) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *PlayerSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerSearchResult) GetOtherNames() []string {
	if x != nil {
		return x.OtherNames
	}
	return nil
}

type SearchPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PlayerSearchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlayersResponse) Reset() {
	*x = SearchPlayersResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlayersResponse) ProtoMessage() {}

func (x *SearchPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlayersResponse.ProtoReflect.Descriptor instead.
func (*SearchPlayersResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{17}
}

func (x *SearchPlayersResponse) GetResults() []*PlayerSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PlayerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHash       string                 `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoRequest) Reset() {
	*x = PlayerInfoRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoRequest) ProtoMessage() {}

func (x *PlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*PlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerInfoRequest) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

type PlayerIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            uint32                 `protobuf:"fixed32,1,opt,name=ip,proto3" json:"ip,omitempty"` // IPv4 address as uint32
	FirstSeen     int64                  `protobuf:"varint,2,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerIP) Reset() {
	*x = PlayerIP{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerIP) ProtoMessage() {}

func (x *PlayerIP) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerIP.ProtoReflect.Descriptor instead.
func (*PlayerIP) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerIP) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

func (x *PlayerIP) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *PlayerIP) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type BanStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ban           *AdminLogEntry         `protobuf:"bytes,1,opt,name=ban,proto3" json:"ban,omitempty"`     // Ban action
	Unban         *AdminLogEntry         `protobuf:"bytes,2,opt,name=unban,proto3" json:"unban,omitempty"` // Unban action (optional, may be null)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanStatus) Reset() {
	*x = BanStatus{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanStatus) ProtoMessage() {}

func (x *BanStatus) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanStatus.ProtoReflect.Descriptor instead.
func (*BanStatus) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{20}
}

func (x *BanStatus) GetBan() *AdminLogEntry {
	if x != nil {
		return x.Ban
	}
	return nil
}

func (x *BanStatus) GetUnban() *AdminLogEntry {
	if x != nil {
		return x.Unban
	}
	return nil
}

type PlayerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHash       string                 `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`                          // All names associated with this hash
	Ips           []*PlayerIP            `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`                              // All IPs associated with this hash
	BanStatus     *BanStatus             `protobuf:"bytes,4,opt,name=ban_status,json=banStatus,proto3" json:"ban_status,omitempty"` // Ban and unban actions (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoResponse) Reset() {
	*x = PlayerInfoResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoResponse) ProtoMessage() {}

func (x *PlayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoResponse.ProtoReflect.Descriptor instead.
func (*PlayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerInfoResponse) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *PlayerInfoResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PlayerInfoResponse) GetIps() []*PlayerIP {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *PlayerInfoResponse) GetBanStatus() *BanStatus {
	if x != nil {
		return x.BanStatus
	}
	return nil
}

type PlayerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHash       string                 `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	FromTimestamp int64                  `protobuf:"varint,2,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"` // Optional: only return logs after this timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogsRequest) Reset() {
	*x = PlayerLogsRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogsRequest) ProtoMessage() {}

func (x *PlayerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogsRequest.ProtoReflect.Descriptor instead.
func (*PlayerLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerLogsRequest) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *PlayerLogsRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

type PlayerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminLogs     []*AdminLogEntry       `protobuf:"bytes,1,rep,name=admin_logs,json=adminLogs,proto3" json:"admin_logs,omitempty"` // Admin actions related to this player
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLogsResponse) Reset() {
	*x = PlayerLogsResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogsResponse) ProtoMessage() {}

func (x *PlayerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogsResponse.ProtoReflect.Descriptor instead.
func (*PlayerLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{23}
}

func (x *PlayerLogsResponse) GetAdminLogs() []*AdminLogEntry {
	if x != nil {
		return x.AdminLogs
	}
	return nil
}

type ConnectedPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHash       string                 `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"` // The keyHash to find connected players for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedPlayersRequest) Reset() {
	*x = ConnectedPlayersRequest{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedPlayersRequest) ProtoMessage() {}

func (x *ConnectedPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedPlayersRequest.ProtoReflect.Descriptor instead.
func (*ConnectedPlayersRequest) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{24}
}

func (x *ConnectedPlayersRequest) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHash       string                 `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`                 // The connected player's keyHash
	ViaKeyHash    string                 `protobuf:"bytes,2,opt,name=via_key_hash,json=viaKeyHash,proto3" json:"via_key_hash,omitempty"`      // The keyHash that led to discovering this
	ViaIp         uint32                 `protobuf:"fixed32,3,opt,name=via_ip,json=viaIp,proto3" json:"via_ip,omitempty"`                     // The IP address that connected them
	DistanceHops  int32                  `protobuf:"varint,4,opt,name=distance_hops,json=distanceHops,proto3" json:"distance_hops,omitempty"` // Number of hops from the original keyHash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{25}
}

func (x *ConnectionInfo) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *ConnectionInfo) GetViaKeyHash() string {
	if x != nil {
		return x.ViaKeyHash
	}
	return ""
}

func (x *ConnectionInfo) GetViaIp() uint32 {
	if x != nil {
		return x.ViaIp
	}
	return 0
}

func (x *ConnectionInfo) GetDistanceHops() int32 {
	if x != nil {
		return x.DistanceHops
	}
	return 0
}

type ConnectedPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*ConnectionInfo      `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"` // How each player is connected to the original keyHash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedPlayersResponse) Reset() {
	*x = ConnectedPlayersResponse{}
	mi := &file_logsproxy_v1_logs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedPlayersResponse) ProtoMessage() {}

func (x *ConnectedPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsproxy_v1_logs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedPlayersResponse.ProtoReflect.Descriptor instead.
func (*ConnectedPlayersResponse) Descriptor() ([]byte, []int) {
	return file_logsproxy_v1_logs_proto_rawDescGZIP(), []int{26}
}

func (x *ConnectedPlayersResponse) GetConnections() []*ConnectionInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_logsproxy_v1_logs_proto protoreflect.FileDescriptor

const file_logsproxy_v1_logs_proto_rawDesc = "" +
	"\n" +
	"\x17logsproxy/v1/logs.proto\x12\flogsproxy.v1\"\xc9\x01\n" +
	"\rAdminLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x121\n" +
	"\x06action\x18\x02 \x01(\x0e2\x19.logsproxy.v1.AdminActionR\x06action\x12\x1d\n" +
	"\n" +
	"action_str\x18\x03 \x01(\tR\tactionStr\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\"N\n" +
	"\x16AdminLogUpdatesRequest\x12$\n" +
	"\vline_number\x18\x01 \x01(\x04H\x00R\n" +
	"lineNumber\x88\x01\x01B\x0e\n" +
	"\f_line_number\"m\n" +
	"\x17AdminLogUpdatesResponse\x121\n" +
	"\x05entry\x18\x01 \x01(\v2\x1b.logsproxy.v1.AdminLogEntryR\x05entry\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x04R\n" +
	"lineNumber\"\x13\n" +
	"\x11AdminsLogsRequest\"K\n" +
	"\x12AdminsLogsResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.logsproxy.v1.AdminLogEntryR\aentries\"\xe4\x01\n" +
	"\fJoinLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bkey_hash\x18\x02 \x01(\tR\akeyHash\x12\x1f\n" +
	"\vtrust_level\x18\x03 \x01(\rR\n" +
	"trustLevel\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04ipv4\x18\x06 \x01(\aR\x04ipv4\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.logsproxy.v1.AccountStatusR\x06status\"M\n" +
	"\x15JoinLogUpdatesRequest\x12$\n" +
	"\vline_number\x18\x01 \x01(\x04H\x00R\n" +
	"lineNumber\x88\x01\x01B\x0e\n" +
	"\f_line_number\"k\n" +
	"\x16JoinLogUpdatesResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.logsproxy.v1.JoinLogEntryR\x05entry\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x04R\n" +
	"lineNumber\"\x11\n" +
	"\x0fJoinLogsRequest\"H\n" +
	"\x10JoinLogsResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.logsproxy.v1.JoinLogEntryR\aentries\"\x8a\x01\n" +
	"\x12PlayerProfileEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bkey_hash\x18\x02 \x01(\tR\akeyHash\x12\x1f\n" +
	"\vtrust_level\x18\x03 \x01(\rR\n" +
	"trustLevel\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"T\n" +
	"\x1cPlayerProfilesUpdatesRequest\x12$\n" +
	"\vline_number\x18\x01 \x01(\x04H\x00R\n" +
	"lineNumber\x88\x01\x01B\x0e\n" +
	"\f_line_number\"x\n" +
	"\x1dPlayerProfilesUpdatesResponse\x126\n" +
	"\x05entry\x18\x01 \x01(\v2 .logsproxy.v1.PlayerProfileEntryR\x05entry\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x04R\n" +
	"lineNumber\"\x1b\n" +
	"\x19PlayerProfilesLogsRequest\"X\n" +
	"\x1aPlayerProfilesLogsResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .logsproxy.v1.PlayerProfileEntryR\aentries\"7\n" +
	"\x14SearchPlayersRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"d\n" +
	"\x12PlayerSearchResult\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vother_names\x18\x03 \x03(\tR\n" +
	"otherNames\"S\n" +
	"\x15SearchPlayersResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .logsproxy.v1.PlayerSearchResultR\aresults\".\n" +
	"\x11PlayerInfoRequest\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\"V\n" +
	"\bPlayerIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\aR\x02ip\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x02 \x01(\x03R\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"m\n" +
	"\tBanStatus\x12-\n" +
	"\x03ban\x18\x01 \x01(\v2\x1b.logsproxy.v1.AdminLogEntryR\x03ban\x121\n" +
	"\x05unban\x18\x02 \x01(\v2\x1b.logsproxy.v1.AdminLogEntryR\x05unban\"\xa7\x01\n" +
	"\x12PlayerInfoResponse\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12(\n" +
	"\x03ips\x18\x03 \x03(\v2\x16.logsproxy.v1.PlayerIPR\x03ips\x126\n" +
	"\n" +
	"ban_status\x18\x04 \x01(\v2\x17.logsproxy.v1.BanStatusR\tbanStatus\"U\n" +
	"\x11PlayerLogsRequest\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\x12%\n" +
	"\x0efrom_timestamp\x18\x02 \x01(\x03R\rfromTimestamp\"P\n" +
	"\x12PlayerLogsResponse\x12:\n" +
	"\n" +
	"admin_logs\x18\x01 \x03(\v2\x1b.logsproxy.v1.AdminLogEntryR\tadminLogs\"4\n" +
	"\x17ConnectedPlayersRequest\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\"\x89\x01\n" +
	"\x0eConnectionInfo\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\x12 \n" +
	"\fvia_key_hash\x18\x02 \x01(\tR\n" +
	"viaKeyHash\x12\x15\n" +
	"\x06via_ip\x18\x03 \x01(\aR\x05viaIp\x12#\n" +
	"\rdistance_hops\x18\x04 \x01(\x05R\fdistanceHops\"Z\n" +
	"\x18ConnectedPlayersResponse\x12>\n" +
	"\vconnections\x18\x01 \x03(\v2\x1c.logsproxy.v1.ConnectionInfoR\vconnections*\x8b\a\n" +
	"\vAdminAction\x12\x1c\n" +
	"\x18ADMIN_ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fADMIN_ACTION_AA\x10\x01\x12\x1a\n" +
	"\x16ADMIN_ACTION_ALLOWEDID\x10\x02\x12\x14\n" +
	"\x10ADMIN_ACTION_BAN\x10\x03\x12\x16\n" +
	"\x12ADMIN_ACTION_BANID\x10\x04\x12\x14\n" +
	"\x10ADMIN_ACTION_FLY\x10\x05\x12\x15\n" +
	"\x11ADMIN_ACTION_HASH\x10\x06\x12\x15\n" +
	"\x11ADMIN_ACTION_INIT\x10\a\x12\x15\n" +
	"\x11ADMIN_ACTION_KICK\x10\b\x12\x15\n" +
	"\x11ADMIN_ACTION_KILL\x10\t\x12\x18\n" +
	"\x14ADMIN_ACTION_MAPVOTE\x10\n" +
	"\x12\x1e\n" +
	"\x1aADMIN_ACTION_MAPVOTERESULT\x10\v\x12\x18\n" +
	"\x14ADMIN_ACTION_MESSAGE\x10\f\x12\x17\n" +
	"\x13ADMIN_ACTION_RELOAD\x10\r\x12\x17\n" +
	"\x13ADMIN_ACTION_REPORT\x10\x0e\x12\x18\n" +
	"\x14ADMIN_ACTION_REPORTP\x10\x0f\x12\x17\n" +
	"\x13ADMIN_ACTION_RESIGN\x10\x10\x12\x1a\n" +
	"\x16ADMIN_ACTION_RESIGNALL\x10\x11\x12\x18\n" +
	"\x14ADMIN_ACTION_RUNNEXT\x10\x12\x12\x14\n" +
	"\x10ADMIN_ACTION_SAY\x10\x13\x12\x18\n" +
	"\x14ADMIN_ACTION_SAYTEAM\x10\x14\x12\x19\n" +
	"\x15ADMIN_ACTION_SCRAMBLE\x10\x15\x12\x18\n" +
	"\x14ADMIN_ACTION_SETNEXT\x10\x16\x12\x1b\n" +
	"\x17ADMIN_ACTION_STOPSERVER\x10\x17\x12\x1a\n" +
	"\x16ADMIN_ACTION_SWAPTEAMS\x10\x18\x12\x17\n" +
	"\x13ADMIN_ACTION_SWITCH\x10\x19\x12\x18\n" +
	"\x14ADMIN_ACTION_TEMPBAN\x10\x1a\x12\x18\n" +
	"\x14ADMIN_ACTION_TICKETS\x10\x1b\x12\x18\n" +
	"\x14ADMIN_ACTION_TIMEBAN\x10\x1c\x12\x1a\n" +
	"\x16ADMIN_ACTION_TIMEBANID\x10\x1d\x12\x16\n" +
	"\x12ADMIN_ACTION_UNBAN\x10\x1e\x12\x18\n" +
	"\x14ADMIN_ACTION_UNBANID\x10\x1f\x12\x1a\n" +
	"\x16ADMIN_ACTION_UNBANNAME\x10 \x12\x18\n" +
	"\x14ADMIN_ACTION_UNGRIEF\x10!\x12\x15\n" +
	"\x11ADMIN_ACTION_WARN\x10\"*\x89\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_LEGACY\x10\x01\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_WHITELISTED\x10\x02\x12\x1d\n" +
	"\x19ACCOUNT_STATUS_VAC_BANNED\x10\x032\xc4\x01\n" +
	"\x0fAdminLogService\x12`\n" +
	"\x0fAdminLogUpdates\x12$.logsproxy.v1.AdminLogUpdatesRequest\x1a%.logsproxy.v1.AdminLogUpdatesResponse0\x01\x12O\n" +
	"\n" +
	"AdminsLogs\x12\x1f.logsproxy.v1.AdminsLogsRequest\x1a .logsproxy.v1.AdminsLogsResponse2\xba\x01\n" +
	"\x0eJoinLogService\x12]\n" +
	"\x0eJoinLogUpdates\x12#.logsproxy.v1.JoinLogUpdatesRequest\x1a$.logsproxy.v1.JoinLogUpdatesResponse0\x01\x12I\n" +
	"\bJoinLogs\x12\x1d.logsproxy.v1.JoinLogsRequest\x1a\x1e.logsproxy.v1.JoinLogsResponse2\xf4\x01\n" +
	"\x15PlayerProfilesService\x12r\n" +
	"\x15PlayerProfilesUpdates\x12*.logsproxy.v1.PlayerProfilesUpdatesRequest\x1a+.logsproxy.v1.PlayerProfilesUpdatesResponse0\x01\x12g\n" +
	"\x12PlayerProfilesLogs\x12'.logsproxy.v1.PlayerProfilesLogsRequest\x1a(.logsproxy.v1.PlayerProfilesLogsResponse2\xf3\x02\n" +
	"\x12PlayerQueryService\x12X\n" +
	"\rSearchPlayers\x12\".logsproxy.v1.SearchPlayersRequest\x1a#.logsproxy.v1.SearchPlayersResponse\x12O\n" +
	"\n" +
	"PlayerInfo\x12\x1f.logsproxy.v1.PlayerInfoRequest\x1a .logsproxy.v1.PlayerInfoResponse\x12O\n" +
	"\n" +
	"PlayerLogs\x12\x1f.logsproxy.v1.PlayerLogsRequest\x1a .logsproxy.v1.PlayerLogsResponse\x12a\n" +
	"\x10ConnectedPlayers\x12%.logsproxy.v1.ConnectedPlayersRequest\x1a&.logsproxy.v1.ConnectedPlayersResponseB:Z8github.com/alliance-community/pr-logs-proxy/logsproxy/v1b\x06proto3"

var (
	file_logsproxy_v1_logs_proto_rawDescOnce sync.Once
	file_logsproxy_v1_logs_proto_rawDescData []byte
)

func file_logsproxy_v1_logs_proto_rawDescGZIP() []byte {
	file_logsproxy_v1_logs_proto_rawDescOnce.Do(func() {
		file_logsproxy_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logsproxy_v1_logs_proto_rawDesc), len(file_logsproxy_v1_logs_proto_rawDesc)))
	})
	return file_logsproxy_v1_logs_proto_rawDescData
}

var file_logsproxy_v1_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_logsproxy_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_logsproxy_v1_logs_proto_goTypes = []any{
	(AdminAction)(0),                      // 0: logsproxy.v1.AdminAction
	(AccountStatus)(0),                    // 1: logsproxy.v1.AccountStatus
	(*AdminLogEntry)(nil),                 // 2: logsproxy.v1.AdminLogEntry
	(*AdminLogUpdatesRequest)(nil),        // 3: logsproxy.v1.AdminLogUpdatesRequest
	(*AdminLogUpdatesResponse)(nil),       // 4: logsproxy.v1.AdminLogUpdatesResponse
	(*AdminsLogsRequest)(nil),             // 5: logsproxy.v1.AdminsLogsRequest
	(*AdminsLogsResponse)(nil),            // 6: logsproxy.v1.AdminsLogsResponse
	(*JoinLogEntry)(nil),                  // 7: logsproxy.v1.JoinLogEntry
	(*JoinLogUpdatesRequest)(nil),         // 8: logsproxy.v1.JoinLogUpdatesRequest
	(*JoinLogUpdatesResponse)(nil),        // 9: logsproxy.v1.JoinLogUpdatesResponse
	(*JoinLogsRequest)(nil),               // 10: logsproxy.v1.JoinLogsRequest
	(*JoinLogsResponse)(nil),              // 11: logsproxy.v1.JoinLogsResponse
	(*PlayerProfileEntry)(nil),            // 12: logsproxy.v1.PlayerProfileEntry
	(*PlayerProfilesUpdatesRequest)(nil),  // 13: logsproxy.v1.PlayerProfilesUpdatesRequest
	(*PlayerProfilesUpdatesResponse)(nil), // 14: logsproxy.v1.PlayerProfilesUpdatesResponse
	(*PlayerProfilesLogsRequest)(nil),     // 15: logsproxy.v1.PlayerProfilesLogsRequest
	(*PlayerProfilesLogsResponse)(nil),    // 16: logsproxy.v1.PlayerProfilesLogsResponse
	(*SearchPlayersRequest)(nil),          // 17: logsproxy.v1.SearchPlayersRequest
	(*PlayerSearchResult)(nil),            // 18: logsproxy.v1.PlayerSearchResult
	(*SearchPlayersResponse)(nil),         // 19: logsproxy.v1.SearchPlayersResponse
	(*PlayerInfoRequest)(nil),             // 20: logsproxy.v1.PlayerInfoRequest
	(*PlayerIP)(nil),                      // 21: logsproxy.v1.PlayerIP
	(*BanStatus)(nil),                     // 22: logsproxy.v1.BanStatus
	(*PlayerInfoResponse)(nil),            // 23: logsproxy.v1.PlayerInfoResponse
	(*PlayerLogsRequest)(nil),             // 24: logsproxy.v1.PlayerLogsRequest
	(*PlayerLogsResponse)(nil),            // 25: logsproxy.v1.PlayerLogsResponse
	(*ConnectedPlayersRequest)(nil),       // 26: logsproxy.v1.ConnectedPlayersRequest
	(*ConnectionInfo)(nil),                // 27: logsproxy.v1.ConnectionInfo
	(*ConnectedPlayersResponse)(nil),      // 28: logsproxy.v1.ConnectedPlayersResponse
}
var file_logsproxy_v1_logs_proto_depIdxs = []int32{
	0,  // 0: logsproxy.v1.AdminLogEntry.action:type_name -> logsproxy.v1.AdminAction
	2,  // 1: logsproxy.v1.AdminLogUpdatesResponse.entry:type_name -> logsproxy.v1.AdminLogEntry
	2,  // 2: logsproxy.v1.AdminsLogsResponse.entries:type_name -> logsproxy.v1.AdminLogEntry
	1,  // 3: logsproxy.v1.JoinLogEntry.status:type_name -> logsproxy.v1.AccountStatus
	7,  // 4: logsproxy.v1.JoinLogUpdatesResponse.entry:type_name -> logsproxy.v1.JoinLogEntry
	7,  // 5: logsproxy.v1.JoinLogsResponse.entries:type_name -> logsproxy.v1.JoinLogEntry
	12, // 6: logsproxy.v1.PlayerProfilesUpdatesResponse.entry:type_name -> logsproxy.v1.PlayerProfileEntry
	12, // 7: logsproxy.v1.PlayerProfilesLogsResponse.entries:type_name -> logsproxy.v1.PlayerProfileEntry
	18, // 8: logsproxy.v1.SearchPlayersResponse.results:type_name -> logsproxy.v1.PlayerSearchResult
	2,  // 9: logsproxy.v1.BanStatus.ban:type_name -> logsproxy.v1.AdminLogEntry
	2,  // 10: logsproxy.v1.BanStatus.unban:type_name -> logsproxy.v1.AdminLogEntry
	21, // 11: logsproxy.v1.PlayerInfoResponse.ips:type_name -> logsproxy.v1.PlayerIP
	22, // 12: logsproxy.v1.PlayerInfoResponse.ban_status:type_name -> logsproxy.v1.BanStatus
	2,  // 13: logsproxy.v1.PlayerLogsResponse.admin_logs:type_name -> logsproxy.v1.AdminLogEntry
	27, // 14: logsproxy.v1.ConnectedPlayersResponse.connections:type_name -> logsproxy.v1.ConnectionInfo
	3,  // 15: logsproxy.v1.AdminLogService.AdminLogUpdates:input_type -> logsproxy.v1.AdminLogUpdatesRequest
	5,  // 16: logsproxy.v1.AdminLogService.AdminsLogs:input_type -> logsproxy.v1.AdminsLogsRequest
	8,  // 17: logsproxy.v1.JoinLogService.JoinLogUpdates:input_type -> logsproxy.v1.JoinLogUpdatesRequest
	10, // 18: logsproxy.v1.JoinLogService.JoinLogs:input_type -> logsproxy.v1.JoinLogsRequest
	13, // 19: logsproxy.v1.PlayerProfilesService.PlayerProfilesUpdates:input_type -> logsproxy.v1.PlayerProfilesUpdatesRequest
	15, // 20: logsproxy.v1.PlayerProfilesService.PlayerProfilesLogs:input_type -> logsproxy.v1.PlayerProfilesLogsRequest
	17, // 21: logsproxy.v1.PlayerQueryService.SearchPlayers:input_type -> logsproxy.v1.SearchPlayersRequest
	20, // 22: logsproxy.v1.PlayerQueryService.PlayerInfo:input_type -> logsproxy.v1.PlayerInfoRequest
	24, // 23: logsproxy.v1.PlayerQueryService.PlayerLogs:input_type -> logsproxy.v1.PlayerLogsRequest
	26, // 24: logsproxy.v1.PlayerQueryService.ConnectedPlayers:input_type -> logsproxy.v1.ConnectedPlayersRequest
	4,  // 25: logsproxy.v1.AdminLogService.AdminLogUpdates:output_type -> logsproxy.v1.AdminLogUpdatesResponse
	6,  // 26: logsproxy.v1.AdminLogService.AdminsLogs:output_type -> logsproxy.v1.AdminsLogsResponse
	9,  // 27: logsproxy.v1.JoinLogService.JoinLogUpdates:output_type -> logsproxy.v1.JoinLogUpdatesResponse
	11, // 28: logsproxy.v1.JoinLogService.JoinLogs:output_type -> logsproxy.v1.JoinLogsResponse
	14, // 29: logsproxy.v1.PlayerProfilesService.PlayerProfilesUpdates:output_type -> logsproxy.v1.PlayerProfilesUpdatesResponse
	16, // 30: logsproxy.v1.PlayerProfilesService.PlayerProfilesLogs:output_type -> logsproxy.v1.PlayerProfilesLogsResponse
	19, // 31: logsproxy.v1.PlayerQueryService.SearchPlayers:output_type -> logsproxy.v1.SearchPlayersResponse
	23, // 32: logsproxy.v1.PlayerQueryService.PlayerInfo:output_type -> logsproxy.v1.PlayerInfoResponse
	25, // 33: logsproxy.v1.PlayerQueryService.PlayerLogs:output_type -> logsproxy.v1.PlayerLogsResponse
	28, // 34: logsproxy.v1.PlayerQueryService.ConnectedPlayers:output_type -> logsproxy.v1.ConnectedPlayersResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_logsproxy_v1_logs_proto_init() }
func file_logsproxy_v1_logs_proto_init() {
	if File_logsproxy_v1_logs_proto != nil {
		return
	}
	file_logsproxy_v1_logs_proto_msgTypes[1].OneofWrappers = []any{}
	file_logsproxy_v1_logs_proto_msgTypes[6].OneofWrappers = []any{}
	file_logsproxy_v1_logs_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logsproxy_v1_logs_proto_rawDesc), len(file_logsproxy_v1_logs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_logsproxy_v1_logs_proto_goTypes,
		DependencyIndexes: file_logsproxy_v1_logs_proto_depIdxs,
		EnumInfos:         file_logsproxy_v1_logs_proto_enumTypes,
		MessageInfos:      file_logsproxy_v1_logs_proto_msgTypes,
	}.Build()
	File_logsproxy_v1_logs_proto = out.File
	file_logsproxy_v1_logs_proto_goTypes = nil
	file_logsproxy_v1_logs_proto_depIdxs = nil
}
