// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: logsproxy/v1/logs.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdminLogService_AdminLogUpdates_FullMethodName = "/logsproxy.v1.AdminLogService/AdminLogUpdates"
	AdminLogService_AdminsLogs_FullMethodName      = "/logsproxy.v1.AdminLogService/AdminsLogs"
)

// AdminLogServiceClient is the client API for AdminLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminLogServiceClient interface {
	AdminLogUpdates(ctx context.Context, in *AdminLogUpdatesRequest, opts ...grpc.CallOption) (AdminLogService_AdminLogUpdatesClient, error)
	AdminsLogs(ctx context.Context, in *AdminsLogsRequest, opts ...grpc.CallOption) (*AdminsLogsResponse, error)
}

type adminLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminLogServiceClient(cc grpc.ClientConnInterface) AdminLogServiceClient {
	return &adminLogServiceClient{cc}
}

func (c *adminLogServiceClient) AdminLogUpdates(ctx context.Context, in *AdminLogUpdatesRequest, opts ...grpc.CallOption) (AdminLogService_AdminLogUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &AdminLogService_ServiceDesc.Streams[0], AdminLogService_AdminLogUpdates_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &adminLogServiceAdminLogUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdminLogService_AdminLogUpdatesClient interface {
	Recv() (*AdminLogUpdatesResponse, error)
	grpc.ClientStream
}

type adminLogServiceAdminLogUpdatesClient struct {
	grpc.ClientStream
}

func (x *adminLogServiceAdminLogUpdatesClient) Recv() (*AdminLogUpdatesResponse, error) {
	m := new(AdminLogUpdatesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adminLogServiceClient) AdminsLogs(ctx context.Context, in *AdminsLogsRequest, opts ...grpc.CallOption) (*AdminsLogsResponse, error) {
	out := new(AdminsLogsResponse)
	err := c.cc.Invoke(ctx, AdminLogService_AdminsLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminLogServiceServer is the server API for AdminLogService service.
// All implementations must embed UnimplementedAdminLogServiceServer
// for forward compatibility
type AdminLogServiceServer interface {
	AdminLogUpdates(*AdminLogUpdatesRequest, AdminLogService_AdminLogUpdatesServer) error
	AdminsLogs(context.Context, *AdminsLogsRequest) (*AdminsLogsResponse, error)
	mustEmbedUnimplementedAdminLogServiceServer()
}

// UnimplementedAdminLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminLogServiceServer struct {
}

func (UnimplementedAdminLogServiceServer) AdminLogUpdates(*AdminLogUpdatesRequest, AdminLogService_AdminLogUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method AdminLogUpdates not implemented")
}
func (UnimplementedAdminLogServiceServer) AdminsLogs(context.Context, *AdminsLogsRequest) (*AdminsLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminsLogs not implemented")
}
func (UnimplementedAdminLogServiceServer) mustEmbedUnimplementedAdminLogServiceServer() {}

// UnsafeAdminLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminLogServiceServer will
// result in compilation errors.
type UnsafeAdminLogServiceServer interface {
	mustEmbedUnimplementedAdminLogServiceServer()
}

func RegisterAdminLogServiceServer(s grpc.ServiceRegistrar, srv AdminLogServiceServer) {
	s.RegisterService(&AdminLogService_ServiceDesc, srv)
}

func _AdminLogService_AdminLogUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AdminLogUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminLogServiceServer).AdminLogUpdates(m, &adminLogServiceAdminLogUpdatesServer{stream})
}

type AdminLogService_AdminLogUpdatesServer interface {
	Send(*AdminLogUpdatesResponse) error
	grpc.ServerStream
}

type adminLogServiceAdminLogUpdatesServer struct {
	grpc.ServerStream
}

func (x *adminLogServiceAdminLogUpdatesServer) Send(m *AdminLogUpdatesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AdminLogService_AdminsLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminsLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLogServiceServer).AdminsLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLogService_AdminsLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLogServiceServer).AdminsLogs(ctx, req.(*AdminsLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminLogService_ServiceDesc is the grpc.ServiceDesc for AdminLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.AdminLogService",
	HandlerType: (*AdminLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminsLogs",
			Handler:    _AdminLogService_AdminsLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AdminLogUpdates",
			Handler:       _AdminLogService_AdminLogUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logsproxy/v1/logs.proto",
}

const (
	JoinLogService_JoinLogUpdates_FullMethodName = "/logsproxy.v1.JoinLogService/JoinLogUpdates"
	JoinLogService_JoinLogs_FullMethodName       = "/logsproxy.v1.JoinLogService/JoinLogs"
)

// JoinLogServiceClient is the client API for JoinLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoinLogServiceClient interface {
	JoinLogUpdates(ctx context.Context, in *JoinLogUpdatesRequest, opts ...grpc.CallOption) (JoinLogService_JoinLogUpdatesClient, error)
	JoinLogs(ctx context.Context, in *JoinLogsRequest, opts ...grpc.CallOption) (*JoinLogsResponse, error)
}

type joinLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJoinLogServiceClient(cc grpc.ClientConnInterface) JoinLogServiceClient {
	return &joinLogServiceClient{cc}
}

func (c *joinLogServiceClient) JoinLogUpdates(ctx context.Context, in *JoinLogUpdatesRequest, opts ...grpc.CallOption) (JoinLogService_JoinLogUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &JoinLogService_ServiceDesc.Streams[0], JoinLogService_JoinLogUpdates_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &joinLogServiceJoinLogUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JoinLogService_JoinLogUpdatesClient interface {
	Recv() (*JoinLogUpdatesResponse, error)
	grpc.ClientStream
}

type joinLogServiceJoinLogUpdatesClient struct {
	grpc.ClientStream
}

func (x *joinLogServiceJoinLogUpdatesClient) Recv() (*JoinLogUpdatesResponse, error) {
	m := new(JoinLogUpdatesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *joinLogServiceClient) JoinLogs(ctx context.Context, in *JoinLogsRequest, opts ...grpc.CallOption) (*JoinLogsResponse, error) {
	out := new(JoinLogsResponse)
	err := c.cc.Invoke(ctx, JoinLogService_JoinLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoinLogServiceServer is the server API for JoinLogService service.
// All implementations must embed UnimplementedJoinLogServiceServer
// for forward compatibility
type JoinLogServiceServer interface {
	JoinLogUpdates(*JoinLogUpdatesRequest, JoinLogService_JoinLogUpdatesServer) error
	JoinLogs(context.Context, *JoinLogsRequest) (*JoinLogsResponse, error)
	mustEmbedUnimplementedJoinLogServiceServer()
}

// UnimplementedJoinLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJoinLogServiceServer struct {
}

func (UnimplementedJoinLogServiceServer) JoinLogUpdates(*JoinLogUpdatesRequest, JoinLogService_JoinLogUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinLogUpdates not implemented")
}
func (UnimplementedJoinLogServiceServer) JoinLogs(context.Context, *JoinLogsRequest) (*JoinLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinLogs not implemented")
}
func (UnimplementedJoinLogServiceServer) mustEmbedUnimplementedJoinLogServiceServer() {}

// UnsafeJoinLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoinLogServiceServer will
// result in compilation errors.
type UnsafeJoinLogServiceServer interface {
	mustEmbedUnimplementedJoinLogServiceServer()
}

func RegisterJoinLogServiceServer(s grpc.ServiceRegistrar, srv JoinLogServiceServer) {
	s.RegisterService(&JoinLogService_ServiceDesc, srv)
}

func _JoinLogService_JoinLogUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinLogUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JoinLogServiceServer).JoinLogUpdates(m, &joinLogServiceJoinLogUpdatesServer{stream})
}

type JoinLogService_JoinLogUpdatesServer interface {
	Send(*JoinLogUpdatesResponse) error
	grpc.ServerStream
}

type joinLogServiceJoinLogUpdatesServer struct {
	grpc.ServerStream
}

func (x *joinLogServiceJoinLogUpdatesServer) Send(m *JoinLogUpdatesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _JoinLogService_JoinLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinLogServiceServer).JoinLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinLogService_JoinLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinLogServiceServer).JoinLogs(ctx, req.(*JoinLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoinLogService_ServiceDesc is the grpc.ServiceDesc for JoinLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoinLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.JoinLogService",
	HandlerType: (*JoinLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinLogs",
			Handler:    _JoinLogService_JoinLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinLogUpdates",
			Handler:       _JoinLogService_JoinLogUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logsproxy/v1/logs.proto",
}

const (
	PlayerProfilesService_PlayerProfilesUpdates_FullMethodName = "/logsproxy.v1.PlayerProfilesService/PlayerProfilesUpdates"
	PlayerProfilesService_PlayerProfilesLogs_FullMethodName    = "/logsproxy.v1.PlayerProfilesService/PlayerProfilesLogs"
)

// PlayerProfilesServiceClient is the client API for PlayerProfilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerProfilesServiceClient interface {
	PlayerProfilesUpdates(ctx context.Context, in *PlayerProfilesUpdatesRequest, opts ...grpc.CallOption) (PlayerProfilesService_PlayerProfilesUpdatesClient, error)
	PlayerProfilesLogs(ctx context.Context, in *PlayerProfilesLogsRequest, opts ...grpc.CallOption) (*PlayerProfilesLogsResponse, error)
}

type playerProfilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerProfilesServiceClient(cc grpc.ClientConnInterface) PlayerProfilesServiceClient {
	return &playerProfilesServiceClient{cc}
}

func (c *playerProfilesServiceClient) PlayerProfilesUpdates(ctx context.Context, in *PlayerProfilesUpdatesRequest, opts ...grpc.CallOption) (PlayerProfilesService_PlayerProfilesUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &PlayerProfilesService_ServiceDesc.Streams[0], PlayerProfilesService_PlayerProfilesUpdates_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &playerProfilesServicePlayerProfilesUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlayerProfilesService_PlayerProfilesUpdatesClient interface {
	Recv() (*PlayerProfilesUpdatesResponse, error)
	grpc.ClientStream
}

type playerProfilesServicePlayerProfilesUpdatesClient struct {
	grpc.ClientStream
}

func (x *playerProfilesServicePlayerProfilesUpdatesClient) Recv() (*PlayerProfilesUpdatesResponse, error) {
	m := new(PlayerProfilesUpdatesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerProfilesServiceClient) PlayerProfilesLogs(ctx context.Context, in *PlayerProfilesLogsRequest, opts ...grpc.CallOption) (*PlayerProfilesLogsResponse, error) {
	out := new(PlayerProfilesLogsResponse)
	err := c.cc.Invoke(ctx, PlayerProfilesService_PlayerProfilesLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerProfilesServiceServer is the server API for PlayerProfilesService service.
// All implementations must embed UnimplementedPlayerProfilesServiceServer
// for forward compatibility
type PlayerProfilesServiceServer interface {
	PlayerProfilesUpdates(*PlayerProfilesUpdatesRequest, PlayerProfilesService_PlayerProfilesUpdatesServer) error
	PlayerProfilesLogs(context.Context, *PlayerProfilesLogsRequest) (*PlayerProfilesLogsResponse, error)
	mustEmbedUnimplementedPlayerProfilesServiceServer()
}

// UnimplementedPlayerProfilesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerProfilesServiceServer struct {
}

func (UnimplementedPlayerProfilesServiceServer) PlayerProfilesUpdates(*PlayerProfilesUpdatesRequest, PlayerProfilesService_PlayerProfilesUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method PlayerProfilesUpdates not implemented")
}
func (UnimplementedPlayerProfilesServiceServer) PlayerProfilesLogs(context.Context, *PlayerProfilesLogsRequest) (*PlayerProfilesLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerProfilesLogs not implemented")
}
func (UnimplementedPlayerProfilesServiceServer) mustEmbedUnimplementedPlayerProfilesServiceServer() {}

// UnsafePlayerProfilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerProfilesServiceServer will
// result in compilation errors.
type UnsafePlayerProfilesServiceServer interface {
	mustEmbedUnimplementedPlayerProfilesServiceServer()
}

func RegisterPlayerProfilesServiceServer(s grpc.ServiceRegistrar, srv PlayerProfilesServiceServer) {
	s.RegisterService(&PlayerProfilesService_ServiceDesc, srv)
}

func _PlayerProfilesService_PlayerProfilesUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayerProfilesUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerProfilesServiceServer).PlayerProfilesUpdates(m, &playerProfilesServicePlayerProfilesUpdatesServer{stream})
}

type PlayerProfilesService_PlayerProfilesUpdatesServer interface {
	Send(*PlayerProfilesUpdatesResponse) error
	grpc.ServerStream
}

type playerProfilesServicePlayerProfilesUpdatesServer struct {
	grpc.ServerStream
}

func (x *playerProfilesServicePlayerProfilesUpdatesServer) Send(m *PlayerProfilesUpdatesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PlayerProfilesService_PlayerProfilesLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerProfilesLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfilesServiceServer).PlayerProfilesLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfilesService_PlayerProfilesLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfilesServiceServer).PlayerProfilesLogs(ctx, req.(*PlayerProfilesLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerProfilesService_ServiceDesc is the grpc.ServiceDesc for PlayerProfilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerProfilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.PlayerProfilesService",
	HandlerType: (*PlayerProfilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayerProfilesLogs",
			Handler:    _PlayerProfilesService_PlayerProfilesLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerProfilesUpdates",
			Handler:       _PlayerProfilesService_PlayerProfilesUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logsproxy/v1/logs.proto",
}

const (
	PlayerQueryService_SearchPlayers_FullMethodName = "/logsproxy.v1.PlayerQueryService/SearchPlayers"
	PlayerQueryService_GetPlayerInfo_FullMethodName = "/logsproxy.v1.PlayerQueryService/GetPlayerInfo"
)

// PlayerQueryServiceClient is the client API for PlayerQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerQueryServiceClient interface {
	SearchPlayers(ctx context.Context, in *PlayerSearchRequest, opts ...grpc.CallOption) (*PlayerSearchResponse, error)
	GetPlayerInfo(ctx context.Context, in *PlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfoResponse, error)
}

type playerQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerQueryServiceClient(cc grpc.ClientConnInterface) PlayerQueryServiceClient {
	return &playerQueryServiceClient{cc}
}

func (c *playerQueryServiceClient) SearchPlayers(ctx context.Context, in *PlayerSearchRequest, opts ...grpc.CallOption) (*PlayerSearchResponse, error) {
	out := new(PlayerSearchResponse)
	err := c.cc.Invoke(ctx, PlayerQueryService_SearchPlayers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerQueryServiceClient) GetPlayerInfo(ctx context.Context, in *PlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfoResponse, error) {
	out := new(PlayerInfoResponse)
	err := c.cc.Invoke(ctx, PlayerQueryService_GetPlayerInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerQueryServiceServer is the server API for PlayerQueryService service.
// All implementations must embed UnimplementedPlayerQueryServiceServer
// for forward compatibility
type PlayerQueryServiceServer interface {
	SearchPlayers(context.Context, *PlayerSearchRequest) (*PlayerSearchResponse, error)
	GetPlayerInfo(context.Context, *PlayerInfoRequest) (*PlayerInfoResponse, error)
	mustEmbedUnimplementedPlayerQueryServiceServer()
}

// UnimplementedPlayerQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerQueryServiceServer struct {
}

func (UnimplementedPlayerQueryServiceServer) SearchPlayers(context.Context, *PlayerSearchRequest) (*PlayerSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPlayers not implemented")
}
func (UnimplementedPlayerQueryServiceServer) GetPlayerInfo(context.Context, *PlayerInfoRequest) (*PlayerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerInfo not implemented")
}
func (UnimplementedPlayerQueryServiceServer) mustEmbedUnimplementedPlayerQueryServiceServer() {}

// UnsafePlayerQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerQueryServiceServer will
// result in compilation errors.
type UnsafePlayerQueryServiceServer interface {
	mustEmbedUnimplementedPlayerQueryServiceServer()
}

func RegisterPlayerQueryServiceServer(s grpc.ServiceRegistrar, srv PlayerQueryServiceServer) {
	s.RegisterService(&PlayerQueryService_ServiceDesc, srv)
}

func _PlayerQueryService_SearchPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerQueryServiceServer).SearchPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerQueryService_SearchPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerQueryServiceServer).SearchPlayers(ctx, req.(*PlayerSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerQueryService_GetPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerQueryServiceServer).GetPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerQueryService_GetPlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerQueryServiceServer).GetPlayerInfo(ctx, req.(*PlayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerQueryService_ServiceDesc is the grpc.ServiceDesc for PlayerQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.PlayerQueryService",
	HandlerType: (*PlayerQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPlayers",
			Handler:    _PlayerQueryService_SearchPlayers_Handler,
		},
		{
			MethodName: "GetPlayerInfo",
			Handler:    _PlayerQueryService_GetPlayerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logsproxy/v1/logs.proto",
}
