// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: logsproxy/v1/logs.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminLogService_AdminLogUpdates_FullMethodName = "/logsproxy.v1.AdminLogService/AdminLogUpdates"
	AdminLogService_AdminsLogs_FullMethodName      = "/logsproxy.v1.AdminLogService/AdminsLogs"
)

// AdminLogServiceClient is the client API for AdminLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminLogServiceClient interface {
	AdminLogUpdates(ctx context.Context, in *AdminLogUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdminLogUpdatesResponse], error)
	AdminsLogs(ctx context.Context, in *AdminsLogsRequest, opts ...grpc.CallOption) (*AdminsLogsResponse, error)
}

type adminLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminLogServiceClient(cc grpc.ClientConnInterface) AdminLogServiceClient {
	return &adminLogServiceClient{cc}
}

func (c *adminLogServiceClient) AdminLogUpdates(ctx context.Context, in *AdminLogUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdminLogUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminLogService_ServiceDesc.Streams[0], AdminLogService_AdminLogUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdminLogUpdatesRequest, AdminLogUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminLogService_AdminLogUpdatesClient = grpc.ServerStreamingClient[AdminLogUpdatesResponse]

func (c *adminLogServiceClient) AdminsLogs(ctx context.Context, in *AdminsLogsRequest, opts ...grpc.CallOption) (*AdminsLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminsLogsResponse)
	err := c.cc.Invoke(ctx, AdminLogService_AdminsLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminLogServiceServer is the server API for AdminLogService service.
// All implementations must embed UnimplementedAdminLogServiceServer
// for forward compatibility.
type AdminLogServiceServer interface {
	AdminLogUpdates(*AdminLogUpdatesRequest, grpc.ServerStreamingServer[AdminLogUpdatesResponse]) error
	AdminsLogs(context.Context, *AdminsLogsRequest) (*AdminsLogsResponse, error)
	mustEmbedUnimplementedAdminLogServiceServer()
}

// UnimplementedAdminLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminLogServiceServer struct{}

func (UnimplementedAdminLogServiceServer) AdminLogUpdates(*AdminLogUpdatesRequest, grpc.ServerStreamingServer[AdminLogUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method AdminLogUpdates not implemented")
}
func (UnimplementedAdminLogServiceServer) AdminsLogs(context.Context, *AdminsLogsRequest) (*AdminsLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminsLogs not implemented")
}
func (UnimplementedAdminLogServiceServer) mustEmbedUnimplementedAdminLogServiceServer() {}
func (UnimplementedAdminLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeAdminLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminLogServiceServer will
// result in compilation errors.
type UnsafeAdminLogServiceServer interface {
	mustEmbedUnimplementedAdminLogServiceServer()
}

func RegisterAdminLogServiceServer(s grpc.ServiceRegistrar, srv AdminLogServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminLogService_ServiceDesc, srv)
}

func _AdminLogService_AdminLogUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AdminLogUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminLogServiceServer).AdminLogUpdates(m, &grpc.GenericServerStream[AdminLogUpdatesRequest, AdminLogUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminLogService_AdminLogUpdatesServer = grpc.ServerStreamingServer[AdminLogUpdatesResponse]

func _AdminLogService_AdminsLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminsLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLogServiceServer).AdminsLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLogService_AdminsLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLogServiceServer).AdminsLogs(ctx, req.(*AdminsLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminLogService_ServiceDesc is the grpc.ServiceDesc for AdminLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.AdminLogService",
	HandlerType: (*AdminLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminsLogs",
			Handler:    _AdminLogService_AdminsLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AdminLogUpdates",
			Handler:       _AdminLogService_AdminLogUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logsproxy/v1/logs.proto",
}

const (
	JoinLogService_JoinLogUpdates_FullMethodName = "/logsproxy.v1.JoinLogService/JoinLogUpdates"
	JoinLogService_JoinLogs_FullMethodName       = "/logsproxy.v1.JoinLogService/JoinLogs"
)

// JoinLogServiceClient is the client API for JoinLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoinLogServiceClient interface {
	JoinLogUpdates(ctx context.Context, in *JoinLogUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JoinLogUpdatesResponse], error)
	JoinLogs(ctx context.Context, in *JoinLogsRequest, opts ...grpc.CallOption) (*JoinLogsResponse, error)
}

type joinLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJoinLogServiceClient(cc grpc.ClientConnInterface) JoinLogServiceClient {
	return &joinLogServiceClient{cc}
}

func (c *joinLogServiceClient) JoinLogUpdates(ctx context.Context, in *JoinLogUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JoinLogUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JoinLogService_ServiceDesc.Streams[0], JoinLogService_JoinLogUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinLogUpdatesRequest, JoinLogUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JoinLogService_JoinLogUpdatesClient = grpc.ServerStreamingClient[JoinLogUpdatesResponse]

func (c *joinLogServiceClient) JoinLogs(ctx context.Context, in *JoinLogsRequest, opts ...grpc.CallOption) (*JoinLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinLogsResponse)
	err := c.cc.Invoke(ctx, JoinLogService_JoinLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoinLogServiceServer is the server API for JoinLogService service.
// All implementations must embed UnimplementedJoinLogServiceServer
// for forward compatibility.
type JoinLogServiceServer interface {
	JoinLogUpdates(*JoinLogUpdatesRequest, grpc.ServerStreamingServer[JoinLogUpdatesResponse]) error
	JoinLogs(context.Context, *JoinLogsRequest) (*JoinLogsResponse, error)
	mustEmbedUnimplementedJoinLogServiceServer()
}

// UnimplementedJoinLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoinLogServiceServer struct{}

func (UnimplementedJoinLogServiceServer) JoinLogUpdates(*JoinLogUpdatesRequest, grpc.ServerStreamingServer[JoinLogUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method JoinLogUpdates not implemented")
}
func (UnimplementedJoinLogServiceServer) JoinLogs(context.Context, *JoinLogsRequest) (*JoinLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinLogs not implemented")
}
func (UnimplementedJoinLogServiceServer) mustEmbedUnimplementedJoinLogServiceServer() {}
func (UnimplementedJoinLogServiceServer) testEmbeddedByValue()                        {}

// UnsafeJoinLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoinLogServiceServer will
// result in compilation errors.
type UnsafeJoinLogServiceServer interface {
	mustEmbedUnimplementedJoinLogServiceServer()
}

func RegisterJoinLogServiceServer(s grpc.ServiceRegistrar, srv JoinLogServiceServer) {
	// If the following call panics, it indicates UnimplementedJoinLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoinLogService_ServiceDesc, srv)
}

func _JoinLogService_JoinLogUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinLogUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JoinLogServiceServer).JoinLogUpdates(m, &grpc.GenericServerStream[JoinLogUpdatesRequest, JoinLogUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JoinLogService_JoinLogUpdatesServer = grpc.ServerStreamingServer[JoinLogUpdatesResponse]

func _JoinLogService_JoinLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinLogServiceServer).JoinLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinLogService_JoinLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinLogServiceServer).JoinLogs(ctx, req.(*JoinLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoinLogService_ServiceDesc is the grpc.ServiceDesc for JoinLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoinLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.JoinLogService",
	HandlerType: (*JoinLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinLogs",
			Handler:    _JoinLogService_JoinLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinLogUpdates",
			Handler:       _JoinLogService_JoinLogUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logsproxy/v1/logs.proto",
}

const (
	PlayerProfilesService_PlayerProfilesUpdates_FullMethodName = "/logsproxy.v1.PlayerProfilesService/PlayerProfilesUpdates"
	PlayerProfilesService_PlayerProfilesLogs_FullMethodName    = "/logsproxy.v1.PlayerProfilesService/PlayerProfilesLogs"
)

// PlayerProfilesServiceClient is the client API for PlayerProfilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerProfilesServiceClient interface {
	PlayerProfilesUpdates(ctx context.Context, in *PlayerProfilesUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerProfilesUpdatesResponse], error)
	PlayerProfilesLogs(ctx context.Context, in *PlayerProfilesLogsRequest, opts ...grpc.CallOption) (*PlayerProfilesLogsResponse, error)
}

type playerProfilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerProfilesServiceClient(cc grpc.ClientConnInterface) PlayerProfilesServiceClient {
	return &playerProfilesServiceClient{cc}
}

func (c *playerProfilesServiceClient) PlayerProfilesUpdates(ctx context.Context, in *PlayerProfilesUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerProfilesUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerProfilesService_ServiceDesc.Streams[0], PlayerProfilesService_PlayerProfilesUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlayerProfilesUpdatesRequest, PlayerProfilesUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerProfilesService_PlayerProfilesUpdatesClient = grpc.ServerStreamingClient[PlayerProfilesUpdatesResponse]

func (c *playerProfilesServiceClient) PlayerProfilesLogs(ctx context.Context, in *PlayerProfilesLogsRequest, opts ...grpc.CallOption) (*PlayerProfilesLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerProfilesLogsResponse)
	err := c.cc.Invoke(ctx, PlayerProfilesService_PlayerProfilesLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerProfilesServiceServer is the server API for PlayerProfilesService service.
// All implementations must embed UnimplementedPlayerProfilesServiceServer
// for forward compatibility.
type PlayerProfilesServiceServer interface {
	PlayerProfilesUpdates(*PlayerProfilesUpdatesRequest, grpc.ServerStreamingServer[PlayerProfilesUpdatesResponse]) error
	PlayerProfilesLogs(context.Context, *PlayerProfilesLogsRequest) (*PlayerProfilesLogsResponse, error)
	mustEmbedUnimplementedPlayerProfilesServiceServer()
}

// UnimplementedPlayerProfilesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerProfilesServiceServer struct{}

func (UnimplementedPlayerProfilesServiceServer) PlayerProfilesUpdates(*PlayerProfilesUpdatesRequest, grpc.ServerStreamingServer[PlayerProfilesUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method PlayerProfilesUpdates not implemented")
}
func (UnimplementedPlayerProfilesServiceServer) PlayerProfilesLogs(context.Context, *PlayerProfilesLogsRequest) (*PlayerProfilesLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerProfilesLogs not implemented")
}
func (UnimplementedPlayerProfilesServiceServer) mustEmbedUnimplementedPlayerProfilesServiceServer() {}
func (UnimplementedPlayerProfilesServiceServer) testEmbeddedByValue()                               {}

// UnsafePlayerProfilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerProfilesServiceServer will
// result in compilation errors.
type UnsafePlayerProfilesServiceServer interface {
	mustEmbedUnimplementedPlayerProfilesServiceServer()
}

func RegisterPlayerProfilesServiceServer(s grpc.ServiceRegistrar, srv PlayerProfilesServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerProfilesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerProfilesService_ServiceDesc, srv)
}

func _PlayerProfilesService_PlayerProfilesUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayerProfilesUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerProfilesServiceServer).PlayerProfilesUpdates(m, &grpc.GenericServerStream[PlayerProfilesUpdatesRequest, PlayerProfilesUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerProfilesService_PlayerProfilesUpdatesServer = grpc.ServerStreamingServer[PlayerProfilesUpdatesResponse]

func _PlayerProfilesService_PlayerProfilesLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerProfilesLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerProfilesServiceServer).PlayerProfilesLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerProfilesService_PlayerProfilesLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerProfilesServiceServer).PlayerProfilesLogs(ctx, req.(*PlayerProfilesLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerProfilesService_ServiceDesc is the grpc.ServiceDesc for PlayerProfilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerProfilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.PlayerProfilesService",
	HandlerType: (*PlayerProfilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayerProfilesLogs",
			Handler:    _PlayerProfilesService_PlayerProfilesLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerProfilesUpdates",
			Handler:       _PlayerProfilesService_PlayerProfilesUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logsproxy/v1/logs.proto",
}

const (
	PlayerQueryService_SearchPlayers_FullMethodName    = "/logsproxy.v1.PlayerQueryService/SearchPlayers"
	PlayerQueryService_PlayerInfo_FullMethodName       = "/logsproxy.v1.PlayerQueryService/PlayerInfo"
	PlayerQueryService_PlayerLogs_FullMethodName       = "/logsproxy.v1.PlayerQueryService/PlayerLogs"
	PlayerQueryService_ConnectedPlayers_FullMethodName = "/logsproxy.v1.PlayerQueryService/ConnectedPlayers"
)

// PlayerQueryServiceClient is the client API for PlayerQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerQueryServiceClient interface {
	SearchPlayers(ctx context.Context, in *SearchPlayersRequest, opts ...grpc.CallOption) (*SearchPlayersResponse, error)
	PlayerInfo(ctx context.Context, in *PlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfoResponse, error)
	PlayerLogs(ctx context.Context, in *PlayerLogsRequest, opts ...grpc.CallOption) (*PlayerLogsResponse, error)
	ConnectedPlayers(ctx context.Context, in *ConnectedPlayersRequest, opts ...grpc.CallOption) (*ConnectedPlayersResponse, error)
}

type playerQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerQueryServiceClient(cc grpc.ClientConnInterface) PlayerQueryServiceClient {
	return &playerQueryServiceClient{cc}
}

func (c *playerQueryServiceClient) SearchPlayers(ctx context.Context, in *SearchPlayersRequest, opts ...grpc.CallOption) (*SearchPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlayersResponse)
	err := c.cc.Invoke(ctx, PlayerQueryService_SearchPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerQueryServiceClient) PlayerInfo(ctx context.Context, in *PlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerInfoResponse)
	err := c.cc.Invoke(ctx, PlayerQueryService_PlayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerQueryServiceClient) PlayerLogs(ctx context.Context, in *PlayerLogsRequest, opts ...grpc.CallOption) (*PlayerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerLogsResponse)
	err := c.cc.Invoke(ctx, PlayerQueryService_PlayerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerQueryServiceClient) ConnectedPlayers(ctx context.Context, in *ConnectedPlayersRequest, opts ...grpc.CallOption) (*ConnectedPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectedPlayersResponse)
	err := c.cc.Invoke(ctx, PlayerQueryService_ConnectedPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerQueryServiceServer is the server API for PlayerQueryService service.
// All implementations must embed UnimplementedPlayerQueryServiceServer
// for forward compatibility.
type PlayerQueryServiceServer interface {
	SearchPlayers(context.Context, *SearchPlayersRequest) (*SearchPlayersResponse, error)
	PlayerInfo(context.Context, *PlayerInfoRequest) (*PlayerInfoResponse, error)
	PlayerLogs(context.Context, *PlayerLogsRequest) (*PlayerLogsResponse, error)
	ConnectedPlayers(context.Context, *ConnectedPlayersRequest) (*ConnectedPlayersResponse, error)
	mustEmbedUnimplementedPlayerQueryServiceServer()
}

// UnimplementedPlayerQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerQueryServiceServer struct{}

func (UnimplementedPlayerQueryServiceServer) SearchPlayers(context.Context, *SearchPlayersRequest) (*SearchPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPlayers not implemented")
}
func (UnimplementedPlayerQueryServiceServer) PlayerInfo(context.Context, *PlayerInfoRequest) (*PlayerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerInfo not implemented")
}
func (UnimplementedPlayerQueryServiceServer) PlayerLogs(context.Context, *PlayerLogsRequest) (*PlayerLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerLogs not implemented")
}
func (UnimplementedPlayerQueryServiceServer) ConnectedPlayers(context.Context, *ConnectedPlayersRequest) (*ConnectedPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectedPlayers not implemented")
}
func (UnimplementedPlayerQueryServiceServer) mustEmbedUnimplementedPlayerQueryServiceServer() {}
func (UnimplementedPlayerQueryServiceServer) testEmbeddedByValue()                            {}

// UnsafePlayerQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerQueryServiceServer will
// result in compilation errors.
type UnsafePlayerQueryServiceServer interface {
	mustEmbedUnimplementedPlayerQueryServiceServer()
}

func RegisterPlayerQueryServiceServer(s grpc.ServiceRegistrar, srv PlayerQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerQueryService_ServiceDesc, srv)
}

func _PlayerQueryService_SearchPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerQueryServiceServer).SearchPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerQueryService_SearchPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerQueryServiceServer).SearchPlayers(ctx, req.(*SearchPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerQueryService_PlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerQueryServiceServer).PlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerQueryService_PlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerQueryServiceServer).PlayerInfo(ctx, req.(*PlayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerQueryService_PlayerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerQueryServiceServer).PlayerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerQueryService_PlayerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerQueryServiceServer).PlayerLogs(ctx, req.(*PlayerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerQueryService_ConnectedPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectedPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerQueryServiceServer).ConnectedPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerQueryService_ConnectedPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerQueryServiceServer).ConnectedPlayers(ctx, req.(*ConnectedPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerQueryService_ServiceDesc is the grpc.ServiceDesc for PlayerQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logsproxy.v1.PlayerQueryService",
	HandlerType: (*PlayerQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPlayers",
			Handler:    _PlayerQueryService_SearchPlayers_Handler,
		},
		{
			MethodName: "PlayerInfo",
			Handler:    _PlayerQueryService_PlayerInfo_Handler,
		},
		{
			MethodName: "PlayerLogs",
			Handler:    _PlayerQueryService_PlayerLogs_Handler,
		},
		{
			MethodName: "ConnectedPlayers",
			Handler:    _PlayerQueryService_ConnectedPlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logsproxy/v1/logs.proto",
}
